[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Info"
  pageRef = "/info/"
  weight = 20

[[main]]
  name = "Speakers"
  pageRef = "/speakers/"
  weight = 25

[[main]]
  name = "Call for Papers"
  pageRef = "/cfp/"
  weight = 30

[[main]]
  name = "Registration"
  pageRef = "/registration/"
  weight = 40

[[main]]
  name = "FAQ"
  pageRef = "/faq/"
  weight = 50

[[main]]
  name = "Code of Conduct"
  pageRef = "/coc/"
  weight = 60

[[main]]
  name = "Contact"
  pageRef = "/contact/"
  weight = 70
